# ->->->->-> Primary <-<-<-<-<-
arch: "vgg16_bn"
exp_name: "temp"
result_dir: "./trained_models"
num_classes: 10
exp_mode: "pretrain"
layer_type: "subnet"
init_type: "kaiming_normal"


# ->->->->-> Pruning <-<-<-<-<-
k: 1.0

# ->->->->-> Train <-<-<-<-<-
trainer: "base"
epochs: 60
optimizer: "adam"
lr: 0.001
lr_schedule: "cosine"
wd: 0.0001
momentum: 0.9
#warmup
warmup_epochs: 0
warmup_lr: 0.1


# ->->->->-> Eval <-<-<-<-<-
val_method: base


# ->->->->-> Dataset <-<-<-<-<-
dataset: CIFAR10
batch_size: 25
test_batch_size: 10
data_dir: "./datasets"
data_fraction: 1.0

# ->->->->-> Semi-supervised training <-<-<-<-<-
semisup_data: "tinyimages"
semisup_fraction: 1.0


# ->->->->-> Adv <-<-<-<-<-
epsilon: 0.007
num_steps: 10
step_size: 0.0078
clip_min: 0
clip_max: 1
distance: "l_inf"
beta: 6.0
starting_epsilon: 0
schedule_length: 10
interval_weight: 0.1


# ->->->->-> Misc <-<-<-<-<-
gpu: "0"
seed: 1234
print_freq: 600