# ->->->->-> Primary <-<-<-<-<-
arch: "ResNet50"
exp_name: "temp"
result_dir: "./trained_models"
num_classes: 1000
exp_mode: "pretrain"
layer_type: "subnet"
init_type: "kaiming_normal"


# ->->->->-> Pruning <-<-<-<-<-
k: 1.0

# ->->->->-> Train <-<-<-<-<-
trainer: "freeadv"
epochs: 90
optimizer: "sgd"
lr: 0.1
lr_schedule: "cosine"
wd: 0.0001
momentum: 0.9
#warmup
warmup_epochs: 0
warmup_lr: 0.1


# ->->->->-> Eval <-<-<-<-<-
val_method: base


# ->->->->-> Dataset <-<-<-<-<-
dataset: imagenet
batch_size: 256
test_batch_size: 256
data_dir: "/data/nvme/imagenet_data/raw-data/"
data_fraction: 1.0
image_dim: 224
mean: !!python/tuple [0.485, 0.456, 0.406]
std: !!python/tuple [0.229, 0.224, 0.225]

# ->->->->-> Adv <-<-<-<-<-
epsilon: 0.0156 #(4/255)
num_steps: 10
step_size: 0.00392 #(1/255)
distance: "l_inf"
beta: 6.0

n_repeats: 4



# ->->->->-> Misc <-<-<-<-<-
gpu: "0,1,2,3"
seed: 1234
print_freq: 10
